version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
      python: 3.7
    commands:
      -  pip install --upgrade 'six==1.15.0'
      -  pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-lightsail-instance"
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-lightsail-instance/rpdk.log"
