AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::Lightsail::Bucket resource type

Globals:
  Function:
    Timeout: 1800  # docker start-up times can be long for SAM CLI
    MemorySize: 2048

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.lightsail.bucket.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-lightsail-bucket-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.lightsail.bucket.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-lightsail-bucket-handler-1.0-SNAPSHOT.jar

